Export Manpages
flatpak/flatpak pull request #4970
Opened 2022-06-28 06:52 UTC by JakobDev

Using Manpages in quite common in Linux. Apps which have more complex command line options are can use Manpages to describe them better. There also some cli programs distributed as Flatpak e.g. org.flatpak.Builder which contains the Builder version used on Flathub. They also would profit from this chance.

2022-07-21 01:56 UTC, mwleeds commented on app/flatpak-builtins-build-finish.c
> +    "share/man/man1",                     /* Manpages */
It doesn't seem clear that section 1 man pages are the only man pages flatpaks might want to export. For example, flatpak-builder is distributed as a flatpak and has a section 5 man page, `flatpak-manifest`. For reference, from `man man`:

```
1.         Executable programs or shell commands
2.         System calls (functions provided by the kernel)
3.         Library calls (functions within program libraries)
4.         Special files (usually found in /dev)
5.         File formats and conventions eg /etc/passwd
6.         Games
7.         Miscellaneous (including macro packages and conventions), e.g. man(7), groff(7)
8.         System administration commands (usually only for root)
9.         Kernel routines [Non standard]
```

2022-07-21 01:57 UTC, mwleeds requested changes
See review comment above

2022-07-21 07:24 UTC, JakobDev commented
Manpages are really fun. The extensions depends on the directory of the Manpages e.g. files in man1 has .1.gz and files in man2 has .2.gz as extension. There are also localised Manpages e.g. de/man1. The code now allows the Export of all files in share/man that has a .gz extension.

2022-07-21 15:10 UTC, mwleeds commented
Have you tested the latest iteration of this branch to make sure it behaves as advertised?

2022-07-22 06:30 UTC, JakobDev commented
> Have you tested the latest iteration of this branch to make sure it behaves as advertised?

Of course

2022-07-22 16:41 UTC, TingPing commented
:-1: This makes no sense. Flatpak doesn't export any binary that a manpage will document.

If you want a manpage for a command inside of a flatpak you can do `flatpak run --command=man org.foo.bar foo`

2022-07-22 21:52 UTC, closed without merging

2022-10-17 14:34 UTC, ibotty commented
Is there a reason this got closed?  I'd certainly like to amend my manpath to include all flatpak manpages.