Russian traslation updated
flatpak/flatpak pull request #5256
Opened 2023-01-12 16:42 UTC by gostsdmitry

2023-01-12 21:49 UTC, gasinvein requested changes

2023-01-12 21:49 UTC, gasinvein commented on po/ru.po
> -"Информация: конец срока поддержки для закреплённого %s//%s наступил в пользу "
Please keep the translation consistent.
"end-of-life" was translated this way in other places, so you should either also change it everywhere, or, better, stick to the current "end-of-life" translation.

2023-01-12 21:49 UTC, gasinvein commented on po/ru.po
> +"Информация: среда выполнения %s%s%s ветвь %s%s%s завершает жизнь, в пользу "
Same here, this change introduces inconsistent "end-of-life" translation.

2023-01-12 21:49 UTC, gasinvein commented on po/ru.po
> +"Информация: приложение %s%s%s ветвь %s%s%s завершает жизнь, в пользу %s
Same here, this change introduces inconsistent "end-of-life" translation.

2023-01-12 21:49 UTC, gasinvein commented on po/ru.po
> +"Информация: (закреплено) среда выполнения %s%s%s ветвь %s%s%s завершает жизнь по "
Same here, this change introduces inconsistent "end-of-life" translation.

2023-01-12 21:49 UTC, gasinvein commented on po/ru.po
> +"Информация: среда выполнения %s%s%s ветвь %s%s%s завершает жизнь по причине:\n"
Same here, this change introduces inconsistent "end-of-life" translation.

2023-01-12 21:49 UTC, gasinvein commented on po/ru.po
> +"Информация: приложение %s%s%s ветвь %s%s%s завершает жизнь по причине:\n"
Same here, this change introduces inconsistent "end-of-life" translation.

2023-01-12 22:53 UTC, gostsdmitry commented
Excuse me, did you block the passage of checks or am I making some mistakes somewhere in the translation file?

2023-01-13 14:51 UTC, gasinvein reviewed
Some nitpicks, otherwise lgtm now.

2023-01-13 14:51 UTC, gasinvein commented on po/ru.po
> +msgstr "Предупреждение: %s%s%s требуется более новая версия flatpak"
```suggestion
msgstr "Предупреждение: %s%s%s требует более новую версию flatpak"
```

2023-01-13 14:51 UTC, gasinvein commented on po/ru.po
> +msgstr "Ошибка: %s%s%s требуется более новая версия flatpak"
```suggestion
msgstr "Ошибка: %s%s%s требует более новую версию flatpak"
```

2023-01-13 14:51 UTC, gasinvein commented on po/ru.po
> +"Информация: (закреплено) среда выполнения %s%s%s ветвь %s%s%s прекращает свое существование, в "
```suggestion
"Информация: (закрепленная) среда выполнения %s%s%s ветвь %s%s%s прекращает свое существование, в "
```

2023-01-13 14:51 UTC, gasinvein commented on po/ru.po
> +"Информация: (закреплено) среда выполнения %s%s%s ветвь %s%s%s прекращает свое существование по "
```suggestion
"Информация: (закрепленная) среда выполнения %s%s%s ветвь %s%s%s прекращает свое существование по "
```

2023-01-13 18:01 UTC, gasinvein approved these changes

2023-01-15 18:27 UTC, merged