dir: Reload DBus daemon config to ensure services get picked up
flatpak/flatpak pull request #5720
Opened 2024-03-11 13:59 UTC by swick

This is best effort. There is a 2s timeout and if something fails everything continues on.

This is called from flatpak_dir_run_triggers because it gets called whenever we might have changes to the exported service files.

2024-03-15 18:36 UTC, smcv requested changes
This seems generally fine, just a style issue.

2024-03-15 18:36 UTC, smcv commented on common/flatpak-dir.c
> +                          "/org/freedesktop/DBus",
Please use consistent indentation:

```
  g_dbus_connection_call_sync (session_bus,
                               "org.freedesktop.DBus",
                               "/org/freedesktop/DBus",
                               (etc.)
```

2024-03-15 18:56 UTC, swick commented on common/flatpak-dir.c
> +                          "/org/freedesktop/DBus",
woops. fixed.

2024-03-20 19:38 UTC, smcv approved these changes

2024-03-20 19:40 UTC, smcv commented
This looks good, but I notice that some of the tests timed out. I've retried in the hope that this was a transient CI issue, rather than this change causing the tests to get stuck for whatever reason.

2024-03-20 19:42 UTC, hfiguiere commented
all my recent PR have been stuck like that. Including changes in doc.

2024-03-20 20:08 UTC, merged