run: Don't inherhit LD_PRELOAD from the host
flatpak/flatpak pull request #5765
Opened 2024-04-04 21:43 UTC by TingPing

I don't think this env var makes much sense to pass into the sandbox for similar reasons to LD_LIBRARY_PATH. Libraries from the host just aren't relevant.

Users can still pass `--env=LD_PRELOAD=/foo` to use this functionality.

2024-04-05 00:45 UTC, Erick555 commented
There is a [comment](https://github.com/flatpak/flatpak/blob/23e78118c3889e9d87f52ba11d3490c9c38e2afe/common/flatpak-run.c#L543) below that says:

>  If updating this list, also update the list in [flatpak-run.xml](https://github.com/flatpak/flatpak/blob/9c059ebdd2812b57b74093b6ff6aba80a31f0548/doc/flatpak-run.xml#L88).

It's easy to miss since it's in the middle of the list so perhaps should be moved on top.

2024-04-05 10:11 UTC, smcv commented
For completeness, we might want to do the same for `LD_AUDIT`, which is like `LD_PRELOAD` but more so.

2024-04-05 10:13 UTC, smcv requested changes
As @Erick555 said, please update the documentation to match. Other than that, this LGTM.

Adding `LD_AUDIT` can be part of this change, or it can be separate.

I would say that changing the organization/layout of this list and its comments as @Erick555 suggested is out-of-scope for this particular PR (but might be a good idea to do separately).

2024-04-05 10:16 UTC, smcv commented
> Users can still pass `--env=LD_PRELOAD=/foo` to use this functionality.

Did you test this? It would be good to know for sure that it's true.

2024-04-08 13:34 UTC, TingPing commented
> Did you test this? It would be good to know for sure that it's true.

Yes I confirmed it works.

2024-04-08 13:41 UTC, smcv commented
> `run: Don't inherhit…`

Typo: should say `inherit`

2024-04-08 13:41 UTC, smcv requested changes
LGTM, other than the typo

2024-04-08 13:53 UTC, TingPing commented
Hmm, I actually hit some failures:

> error: Can't open generated ld.so.cache

So I'll check this out later.

2024-04-08 13:56 UTC, TingPing commented
Hmm, this happens on `main`, so it must be a badly configured build, but I'll verify everything is good before merging.

2024-04-24 11:20 UTC, smcv approved these changes

2024-04-24 11:21 UTC, smcv commented
> I'll verify everything is good before merging

Not merging this right now because it's still marked as draft, but the change looks good, so please re-test.

2024-04-24 15:03 UTC, merged