Add FLATPAK_OS_CONFIG_DIR environment variable
flatpak/flatpak pull request #5994
Opened 2024-11-06 18:33 UTC by owtaylor

Now that we read remotes from `$datadir/flatpaks/remotes.d` as well as `/etc/flatpaks/remotes.d`, we should have a mechanism to redirect this, as we do for almost all other filesystem path locations.

To avoid an explosion of new variables, we introduce `FLATPAK_OS_CONFIG_DIR` to represent configuration that ships with the operating system.

This is useful:

 * To fix sandboxing of tests
 * When installing using flatpak into a chroot, so that we read the chroot's configuration rather than the host.

It also is used when reading triggers, but the current `FLATPAK_TRIGGERSDIR` is left for compatibility.

---

Notes:

* Should this apply to trigger at all? Are the triggers really configuration?
* If it *should* apply for triggers, then do we need compat handling of `FLATPAK_TRIGGERSDIR`?

2024-11-11 20:02 UTC, swick reviewed
Makes sense and LGTM when the trivial style issue is fixed.

2024-11-28 19:03 UTC, smcv requested changes
I like this change, and I think we should get it into 1.16.0. But I don't much like the name - I would expect `FLATPAK_OS_CONFIG_DIR` to be `/etc`.

Perhaps `FLATPAK_DATADIR` or `FLATPAK_SHARE_DIR` or `FLATPAK_DEFAULTS_DIR`? (Those are in my personal preference order, most-preferred first.)

I was tempted to suggest `FLATPAK_BASEDIR`, because that name already exists as a cpp macro, but I think that might be confusable with `/var/lib/flatpak` so maybe a clean slate is better.

2024-11-28 19:04 UTC, smcv commented
> * Should this apply to trigger at all? Are the triggers really configuration?

No, but they are data, so my suggested renaming of the variable would resolve this concern.

> * If it _should_ apply for triggers, then do we need compat handling of `FLATPAK_TRIGGERSDIR`?

I think the compat handling costs us very little.

2024-12-18 06:32 UTC, owtaylor commented
> I like this change, and I think we should get it into 1.16.0. But I don't much like the name - I would expect `FLATPAK_OS_CONFIG_DIR` to be `/etc`.
> 
> Perhaps `FLATPAK_DATADIR` or `FLATPAK_SHARE_DIR` or `FLATPAK_DEFAULTS_DIR`? (Those are in my personal preference order, most-preferred first.)
> 
> I was tempted to suggest `FLATPAK_BASEDIR`, because that name already exists as a cpp macro, but I think that might be confusable with `/var/lib/flatpak` so maybe a clean slate is better.

The idea of "OS_CONFIG_DIR" is "configuration that ships with the operating system" - as opposed to /etc - e.g. "sysconfdir" - which is configuration that applies to the local system. The whole idea of having /usr/share/flatpak/remotes.d is that distro configuration should go there and be separated from local configuration.

To quote Pablo in 0313df972a61 "It is better practice to put things under /usr/share, and let the system administrator modify /etc to their will, of course giving them priority."

But that being said, yes, perhaps it is too clever. I'd be fine with `FLATPAK_DATADIR`.

2024-12-18 13:23 UTC, swick commented
Fixed the code review issues, renamed to `FLATPAK_DATA_DIR`, left the triggers compat handling intact.

2024-12-18 16:31 UTC, smcv approved these changes

2024-12-18 16:32 UTC, merged